service: mylambda
plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
     - local
     - dev
    endpointFile: localstack_endpoints.json
    
provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
