service: api

plugins:
  - serverless-offline
 
provider:
  name: aws
  runtime: python3.11
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: s3
          method: post
  get:
    handler: handler.get
    events:
      - http:
          path: s3
          method: get